//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QbSoapService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://developer.intuit.com/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://developer.intuit.com/", ConfigurationName="QbSoapService.IQuickBooksService")]
    public interface IQuickBooksService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/IQuickBooksService/authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<QbSoapService.authenticateResponse> authenticateAsync(QbSoapService.authenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/IQuickBooksService/clientVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<QbSoapService.clientVersionResponse> clientVersionAsync(QbSoapService.clientVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/IQuickBooksService/serverVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<QbSoapService.serverVersionResponse> serverVersionAsync(QbSoapService.serverVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/IQuickBooksService/sendRequestXML", ReplyAction="*")]
        System.Threading.Tasks.Task<QbSoapService.sendRequestXMLResponse> sendRequestXMLAsync(QbSoapService.sendRequestXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/IQuickBooksService/receiveResponseXML", ReplyAction="*")]
        System.Threading.Tasks.Task<QbSoapService.receiveResponseXMLResponse> receiveResponseXMLAsync(QbSoapService.receiveResponseXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/IQuickBooksService/connectionError", ReplyAction="*")]
        System.Threading.Tasks.Task<QbSoapService.connectionErrorResponse> connectionErrorAsync(QbSoapService.connectionErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/IQuickBooksService/closeConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<QbSoapService.closeConnectionResponse> closeConnectionAsync(QbSoapService.closeConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://developer.intuit.com/IQuickBooksService/getLastError", ReplyAction="*")]
        System.Threading.Tasks.Task<QbSoapService.getLastErrorResponse> getLastErrorAsync(QbSoapService.getLastErrorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticate", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.authenticateRequestBody Body;
        
        public authenticateRequest()
        {
        }
        
        public authenticateRequest(QbSoapService.authenticateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class authenticateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public authenticateRequestBody()
        {
        }
        
        public authenticateRequestBody(string strUserName, string strPassword)
        {
            this.strUserName = strUserName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="authenticateResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.authenticateResponseBody Body;
        
        public authenticateResponse()
        {
        }
        
        public authenticateResponse(QbSoapService.authenticateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class authenticateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public QbSoapService.ArrayOfString authenticateResult;
        
        public authenticateResponseBody()
        {
        }
        
        public authenticateResponseBody(QbSoapService.ArrayOfString authenticateResult)
        {
            this.authenticateResult = authenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clientVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clientVersion", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.clientVersionRequestBody Body;
        
        public clientVersionRequest()
        {
        }
        
        public clientVersionRequest(QbSoapService.clientVersionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class clientVersionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strVersion;
        
        public clientVersionRequestBody()
        {
        }
        
        public clientVersionRequestBody(string strVersion)
        {
            this.strVersion = strVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clientVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clientVersionResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.clientVersionResponseBody Body;
        
        public clientVersionResponse()
        {
        }
        
        public clientVersionResponse(QbSoapService.clientVersionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class clientVersionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientVersionResult;
        
        public clientVersionResponseBody()
        {
        }
        
        public clientVersionResponseBody(string clientVersionResult)
        {
            this.clientVersionResult = clientVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class serverVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="serverVersion", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.serverVersionRequestBody Body;
        
        public serverVersionRequest()
        {
        }
        
        public serverVersionRequest(QbSoapService.serverVersionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class serverVersionRequestBody
    {
        
        public serverVersionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class serverVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="serverVersionResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.serverVersionResponseBody Body;
        
        public serverVersionResponse()
        {
        }
        
        public serverVersionResponse(QbSoapService.serverVersionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class serverVersionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serverVersionResult;
        
        public serverVersionResponseBody()
        {
        }
        
        public serverVersionResponseBody(string serverVersionResult)
        {
            this.serverVersionResult = serverVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRequestXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRequestXML", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.sendRequestXMLRequestBody Body;
        
        public sendRequestXMLRequest()
        {
        }
        
        public sendRequestXMLRequest(QbSoapService.sendRequestXMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class sendRequestXMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strHCPResponse;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strCompanyFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string qbXMLCountry;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int qbXMLMajorVers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int qbXMLMinorVers;
        
        public sendRequestXMLRequestBody()
        {
        }
        
        public sendRequestXMLRequestBody(string ticket, string strHCPResponse, string strCompanyFileName, string qbXMLCountry, int qbXMLMajorVers, int qbXMLMinorVers)
        {
            this.ticket = ticket;
            this.strHCPResponse = strHCPResponse;
            this.strCompanyFileName = strCompanyFileName;
            this.qbXMLCountry = qbXMLCountry;
            this.qbXMLMajorVers = qbXMLMajorVers;
            this.qbXMLMinorVers = qbXMLMinorVers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRequestXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRequestXMLResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.sendRequestXMLResponseBody Body;
        
        public sendRequestXMLResponse()
        {
        }
        
        public sendRequestXMLResponse(QbSoapService.sendRequestXMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class sendRequestXMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sendRequestXMLResult;
        
        public sendRequestXMLResponseBody()
        {
        }
        
        public sendRequestXMLResponseBody(string sendRequestXMLResult)
        {
            this.sendRequestXMLResult = sendRequestXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveResponseXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveResponseXML", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.receiveResponseXMLRequestBody Body;
        
        public receiveResponseXMLRequest()
        {
        }
        
        public receiveResponseXMLRequest(QbSoapService.receiveResponseXMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class receiveResponseXMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string response;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hresult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string message;
        
        public receiveResponseXMLRequestBody()
        {
        }
        
        public receiveResponseXMLRequestBody(string ticket, string response, string hresult, string message)
        {
            this.ticket = ticket;
            this.response = response;
            this.hresult = hresult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class receiveResponseXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="receiveResponseXMLResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.receiveResponseXMLResponseBody Body;
        
        public receiveResponseXMLResponse()
        {
        }
        
        public receiveResponseXMLResponse(QbSoapService.receiveResponseXMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class receiveResponseXMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int receiveResponseXMLResult;
        
        public receiveResponseXMLResponseBody()
        {
        }
        
        public receiveResponseXMLResponseBody(int receiveResponseXMLResult)
        {
            this.receiveResponseXMLResult = receiveResponseXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class connectionErrorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="connectionError", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.connectionErrorRequestBody Body;
        
        public connectionErrorRequest()
        {
        }
        
        public connectionErrorRequest(QbSoapService.connectionErrorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class connectionErrorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hresult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public connectionErrorRequestBody()
        {
        }
        
        public connectionErrorRequestBody(string ticket, string hresult, string message)
        {
            this.ticket = ticket;
            this.hresult = hresult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class connectionErrorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="connectionErrorResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.connectionErrorResponseBody Body;
        
        public connectionErrorResponse()
        {
        }
        
        public connectionErrorResponse(QbSoapService.connectionErrorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class connectionErrorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string connectionErrorResult;
        
        public connectionErrorResponseBody()
        {
        }
        
        public connectionErrorResponseBody(string connectionErrorResult)
        {
            this.connectionErrorResult = connectionErrorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeConnectionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeConnection", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.closeConnectionRequestBody Body;
        
        public closeConnectionRequest()
        {
        }
        
        public closeConnectionRequest(QbSoapService.closeConnectionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class closeConnectionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        public closeConnectionRequestBody()
        {
        }
        
        public closeConnectionRequestBody(string ticket)
        {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class closeConnectionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="closeConnectionResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.closeConnectionResponseBody Body;
        
        public closeConnectionResponse()
        {
        }
        
        public closeConnectionResponse(QbSoapService.closeConnectionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class closeConnectionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string closeConnectionResult;
        
        public closeConnectionResponseBody()
        {
        }
        
        public closeConnectionResponseBody(string closeConnectionResult)
        {
            this.closeConnectionResult = closeConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastErrorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastError", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.getLastErrorRequestBody Body;
        
        public getLastErrorRequest()
        {
        }
        
        public getLastErrorRequest(QbSoapService.getLastErrorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class getLastErrorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticket;
        
        public getLastErrorRequestBody()
        {
        }
        
        public getLastErrorRequestBody(string ticket)
        {
            this.ticket = ticket;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastErrorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastErrorResponse", Namespace="http://developer.intuit.com/", Order=0)]
        public QbSoapService.getLastErrorResponseBody Body;
        
        public getLastErrorResponse()
        {
        }
        
        public getLastErrorResponse(QbSoapService.getLastErrorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://developer.intuit.com/")]
    public partial class getLastErrorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getLastErrorResult;
        
        public getLastErrorResponseBody()
        {
        }
        
        public getLastErrorResponseBody(string getLastErrorResult)
        {
            this.getLastErrorResult = getLastErrorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IQuickBooksServiceChannel : QbSoapService.IQuickBooksService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class QuickBooksServiceClient : System.ServiceModel.ClientBase<QbSoapService.IQuickBooksService>, QbSoapService.IQuickBooksService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public QuickBooksServiceClient() : 
                base(QuickBooksServiceClient.GetDefaultBinding(), QuickBooksServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IQuickBooksService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuickBooksServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(QuickBooksServiceClient.GetBindingForEndpoint(endpointConfiguration), QuickBooksServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuickBooksServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(QuickBooksServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuickBooksServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(QuickBooksServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuickBooksServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QbSoapService.authenticateResponse> QbSoapService.IQuickBooksService.authenticateAsync(QbSoapService.authenticateRequest request)
        {
            return base.Channel.authenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<QbSoapService.authenticateResponse> authenticateAsync(string strUserName, string strPassword)
        {
            QbSoapService.authenticateRequest inValue = new QbSoapService.authenticateRequest();
            inValue.Body = new QbSoapService.authenticateRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            return ((QbSoapService.IQuickBooksService)(this)).authenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QbSoapService.clientVersionResponse> QbSoapService.IQuickBooksService.clientVersionAsync(QbSoapService.clientVersionRequest request)
        {
            return base.Channel.clientVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<QbSoapService.clientVersionResponse> clientVersionAsync(string strVersion)
        {
            QbSoapService.clientVersionRequest inValue = new QbSoapService.clientVersionRequest();
            inValue.Body = new QbSoapService.clientVersionRequestBody();
            inValue.Body.strVersion = strVersion;
            return ((QbSoapService.IQuickBooksService)(this)).clientVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QbSoapService.serverVersionResponse> QbSoapService.IQuickBooksService.serverVersionAsync(QbSoapService.serverVersionRequest request)
        {
            return base.Channel.serverVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<QbSoapService.serverVersionResponse> serverVersionAsync()
        {
            QbSoapService.serverVersionRequest inValue = new QbSoapService.serverVersionRequest();
            inValue.Body = new QbSoapService.serverVersionRequestBody();
            return ((QbSoapService.IQuickBooksService)(this)).serverVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QbSoapService.sendRequestXMLResponse> QbSoapService.IQuickBooksService.sendRequestXMLAsync(QbSoapService.sendRequestXMLRequest request)
        {
            return base.Channel.sendRequestXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<QbSoapService.sendRequestXMLResponse> sendRequestXMLAsync(string ticket, string strHCPResponse, string strCompanyFileName, string qbXMLCountry, int qbXMLMajorVers, int qbXMLMinorVers)
        {
            QbSoapService.sendRequestXMLRequest inValue = new QbSoapService.sendRequestXMLRequest();
            inValue.Body = new QbSoapService.sendRequestXMLRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.strHCPResponse = strHCPResponse;
            inValue.Body.strCompanyFileName = strCompanyFileName;
            inValue.Body.qbXMLCountry = qbXMLCountry;
            inValue.Body.qbXMLMajorVers = qbXMLMajorVers;
            inValue.Body.qbXMLMinorVers = qbXMLMinorVers;
            return ((QbSoapService.IQuickBooksService)(this)).sendRequestXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QbSoapService.receiveResponseXMLResponse> QbSoapService.IQuickBooksService.receiveResponseXMLAsync(QbSoapService.receiveResponseXMLRequest request)
        {
            return base.Channel.receiveResponseXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<QbSoapService.receiveResponseXMLResponse> receiveResponseXMLAsync(string ticket, string response, string hresult, string message)
        {
            QbSoapService.receiveResponseXMLRequest inValue = new QbSoapService.receiveResponseXMLRequest();
            inValue.Body = new QbSoapService.receiveResponseXMLRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.response = response;
            inValue.Body.hresult = hresult;
            inValue.Body.message = message;
            return ((QbSoapService.IQuickBooksService)(this)).receiveResponseXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QbSoapService.connectionErrorResponse> QbSoapService.IQuickBooksService.connectionErrorAsync(QbSoapService.connectionErrorRequest request)
        {
            return base.Channel.connectionErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<QbSoapService.connectionErrorResponse> connectionErrorAsync(string ticket, string hresult, string message)
        {
            QbSoapService.connectionErrorRequest inValue = new QbSoapService.connectionErrorRequest();
            inValue.Body = new QbSoapService.connectionErrorRequestBody();
            inValue.Body.ticket = ticket;
            inValue.Body.hresult = hresult;
            inValue.Body.message = message;
            return ((QbSoapService.IQuickBooksService)(this)).connectionErrorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QbSoapService.closeConnectionResponse> QbSoapService.IQuickBooksService.closeConnectionAsync(QbSoapService.closeConnectionRequest request)
        {
            return base.Channel.closeConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<QbSoapService.closeConnectionResponse> closeConnectionAsync(string ticket)
        {
            QbSoapService.closeConnectionRequest inValue = new QbSoapService.closeConnectionRequest();
            inValue.Body = new QbSoapService.closeConnectionRequestBody();
            inValue.Body.ticket = ticket;
            return ((QbSoapService.IQuickBooksService)(this)).closeConnectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QbSoapService.getLastErrorResponse> QbSoapService.IQuickBooksService.getLastErrorAsync(QbSoapService.getLastErrorRequest request)
        {
            return base.Channel.getLastErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<QbSoapService.getLastErrorResponse> getLastErrorAsync(string ticket)
        {
            QbSoapService.getLastErrorRequest inValue = new QbSoapService.getLastErrorRequest();
            inValue.Body = new QbSoapService.getLastErrorRequestBody();
            inValue.Body.ticket = ticket;
            return ((QbSoapService.IQuickBooksService)(this)).getLastErrorAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IQuickBooksService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IQuickBooksService_soap))
            {
                return new System.ServiceModel.EndpointAddress("https://bmk-api.live1.dev.radixweb.net/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return QuickBooksServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IQuickBooksService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return QuickBooksServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IQuickBooksService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IQuickBooksService_soap,
        }
    }
}
